config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
	
  resources :clientes
  resources :cli_sistemas
  #root :to => "cli_sistemas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cli_sistema.rb
class CliSistema < ApplicationRecord
	validates :password, length: {minimum: 6},
				presence: true
	validates :name, presence: true
	validates :user, presence: true
	validates :tipo, presence: true
	validates :domicilio, presence: true
	validates :RFC, presence: true
	validates :representante, presence: true
	validates :CP, presence: true
	validates :phone, presence: true
	validates :email, presence: true
	validates :CURP, presence: true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cli_sistemas_controller.rb
class CliSistemasController < ApplicationController
  before_action :set_cli_sistema, only: [:show, :edit, :update, :destroy]

  # GET /cli_sistemas
  # GET /cli_sistemas.json
  def index
    @cli_sistemas = CliSistema.all
  end

  # GET /cli_sistemas/1
  # GET /cli_sistemas/1.json
  def show
  end

  # GET /cli_sistemas/new
  def new
    @cli_sistema = CliSistema.new
  end

  # GET /cli_sistemas/1/edit
  def edit
  end

  # POST /cli_sistemas
  # POST /cli_sistemas.json
  def create
    @cli_sistema = CliSistema.new(cli_sistema_params)

    respond_to do |format|
      if @cli_sistema.save
        format.html { redirect_to @cli_sistema, notice: 'Cli sistema was successfully created.' }
        format.json { render :show, status: :created, location: @cli_sistema }
      else
        format.html { render :new }
        format.json { render json: @cli_sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cli_sistemas/1
  # PATCH/PUT /cli_sistemas/1.json
  def update
    respond_to do |format|
      if @cli_sistema.update(cli_sistema_params)
        format.html { redirect_to @cli_sistema, notice: 'Cli sistema was successfully updated.' }
        format.json { render :show, status: :ok, location: @cli_sistema }
      else
        format.html { render :edit }
        format.json { render json: @cli_sistema.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cli_sistemas/1
  # DELETE /cli_sistemas/1.json
  def destroy
    @cli_sistema.destroy
    respond_to do |format|
      format.html { redirect_to cli_sistemas_url, notice: 'Cli sistema was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cli_sistema
      @cli_sistema = CliSistema.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cli_sistema_params
      params.require(:cli_sistema).permit(:name, :user, :password, :tipo, :domicilio, :RFC, :representante, :CP, :phone, :email, :CURP)
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:name, :tipoPersona, :domicilio, :rfc, :cp, :phone, :email)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cli_sistemas_helper.rb
module CliSistemasHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cli_sistemas/_form.html.erb
<%= form_for(cli_sistema) do |f| %>
  <% if cli_sistema.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cli_sistema.errors.count, "error") %> prohibited this cli_sistema from being saved:</h2>

      <ul>
      <% cli_sistema.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.label :tipo, "Física", :value => "Fisica"  %>
    <%= f.radio_button :tipo, true %>
    <%= f.label :tipo, "Moral", :value => "Moral" %>
    <%= f.radio_button :tipo, false, :checked => true %>
  </div>

  <div class="field">
    <%= f.label :domicilio %>
    <%= f.text_field :domicilio %>
  </div>

  <div class="field">
    <%= f.label :RFC %>
    <%= f.text_field :RFC %>
  </div>

  <div class="field">
    <%= f.label :representante %>
    <%= f.text_field :representante %>
  </div>

  <div class="field">
    <%= f.label :CP %>
    <%= f.text_field :CP %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :CURP %>
    <%= f.text_field :CURP %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cli_sistemas/edit.html.erb
<h1>Editing Cli Sistema</h1>

<%= render 'form', cli_sistema: @cli_sistema %>

<%= link_to 'Show', @cli_sistema %> |
<%= link_to 'Back', cli_sistemas_path %>

app/views/cli_sistemas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cli Sistemas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Usuario</th>
      <th>Tipo</th>
      <th>Domicilio</th>
      <th>RFC</th>
      <th>Representante Legal</th>
      <th>CP</th>
      <th>Teléfono</th>
      <th>Correo</th>
      <th>CURP</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cli_sistemas.each do |cli_sistema| %>
      <tr>
        <td><%= cli_sistema.name %></td>
        <td><%= cli_sistema.user %></td>
        <td><%= cli_sistema.tipo %></td>
        <td><%= cli_sistema.domicilio %></td>
        <td><%= cli_sistema.RFC %></td>
        <td><%= cli_sistema.representante %></td>
        <td><%= cli_sistema.CP %></td>
        <td><%= cli_sistema.phone %></td>
        <td><%= cli_sistema.email %></td>
        <td><%= cli_sistema.CURP %></td>
        <td><%= link_to 'Ver', cli_sistema %></td>
        <td><%= link_to 'Editar', edit_cli_sistema_path(cli_sistema) %></td>
        <td><%= link_to 'Borrar', cli_sistema, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cli Sistema', new_cli_sistema_path %>

app/views/cli_sistemas/new.html.erb
<h1>New Cli Sistema</h1>

<%= render 'form', cli_sistema: @cli_sistema %>

<%= link_to 'Back', cli_sistemas_path %>

app/views/cli_sistemas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cli_sistema.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @cli_sistema.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @cli_sistema.password %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @cli_sistema.tipo %>
</p>

<p>
  <strong>Domicilio:</strong>
  <%= @cli_sistema.domicilio %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @cli_sistema.RFC %>
</p>

<p>
  <strong>Representante:</strong>
  <%= @cli_sistema.representante %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @cli_sistema.CP %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @cli_sistema.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cli_sistema.email %>
</p>

<p>
  <strong>Curp:</strong>
  <%= @cli_sistema.CURP %>
</p>

<%= link_to 'Edit', edit_cli_sistema_path(@cli_sistema) %> |
<%= link_to 'Back', cli_sistemas_path %>

app/views/clientes/_form.html.erb
<%= form_for(cliente) do |f| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :tipoPersona %>
    <%= f.text_field :tipoPersona %>
  </div>

  <div class="field">
    <%= f.label :domicilio %>
    <%= f.text_field :domicilio %>
  </div>

  <div class="field">
    <%= f.label :rfc %>
    <%= f.text_field :rfc %>
  </div>

  <div class="field">
    <%= f.label :cp %>
    <%= f.text_field :cp %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tipopersona</th>
      <th>Domicilio</th>
      <th>Rfc</th>
      <th>Cp</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.name %></td>
        <td><%= cliente.tipoPersona %></td>
        <td><%= cliente.domicilio %></td>
        <td><%= cliente.rfc %></td>
        <td><%= cliente.cp %></td>
        <td><%= cliente.phone %></td>
        <td><%= cliente.email %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Tipopersona:</strong>
  <%= @cliente.tipoPersona %>
</p>

<p>
  <strong>Domicilio:</strong>
  <%= @cliente.domicilio %>
</p>

<p>
  <strong>Rfc:</strong>
  <%= @cliente.rfc %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @cliente.cp %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @cliente.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Facturo-OnLine</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Inicio") %>
<h1>Home</h1>
<p>
	Facturo online
</p>